import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { blogPosts, featuredBlogPost } from "../data/blog-posts.mjs";
import { renderFontHead } from "./render-performance-head.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const homeTarget = resolve(root, "index.html");
const blogDirectory = resolve(root, "blog");
const homeStart = "        <!-- blog:home:start -->";
const homeEnd = "        <!-- blog:home:end -->";
const generatedNote = "<!-- This file is generated by scripts/generate-blog.mjs. Edit data/blog-posts.mjs instead. -->";
const checkMode = process.argv.includes("--check");

const escapeHtml = (value) => String(value)
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;");

const formatDate = (date) => new Intl.DateTimeFormat("pt-BR", {
  day: "numeric",
  month: "long",
  year: "numeric",
  timeZone: "UTC",
}).format(new Date(`${date}T12:00:00Z`));

const jsonLd = (value) => JSON.stringify(value).replaceAll("<", "\\u003c");

function whatsappUrl(message) {
  return `https://wa.me/5583994212431?text=${encodeURIComponent(message)}`;
}

function whatsappIcon() {
  return '<svg viewBox="0 0 32 32" width="26" height="26" aria-hidden="true"><path fill="currentColor" d="M16 3C9.4 3 4 8.4 4 15c0 2.1.5 4.1 1.6 5.9L4 29l8.3-1.5c1.7.9 3.6 1.4 5.7 1.4 6.6 0 12-5.4 12-12S22.6 3 16 3zm0 21.8c-1.8 0-3.5-.5-5-1.4l-.4-.2-4.9.9.9-4.8-.2-.4c-1-1.6-1.5-3.4-1.5-5.3 0-5.6 4.6-10.2 10.2-10.2S26.2 9.4 26.2 15 21.6 24.8 16 24.8zm5.6-7.6c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2-.2.3-.8 1-.9 1.2-.2.2-.3.2-.6.1-.3-.2-1.3-.5-2.5-1.5-.9-.8-1.5-1.8-1.7-2.1-.2-.3 0-.5.1-.6.1-.1.3-.3.4-.5.2-.2.2-.3.3-.5.1-.2 0-.4 0-.5-.1-.2-.7-1.6-.9-2.2-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.5.1-.8.4-.3.3-1 1-1 2.5s1.1 2.9 1.2 3.1c.2.2 2.1 3.2 5.1 4.5.7.3 1.3.5 1.7.6.7.2 1.4.2 1.9.1.6-.1 1.8-.7 2-1.5.3-.7.3-1.4.2-1.5-.1-.1-.3-.2-.6-.4z" /></svg>';
}

function renderHeader(assetPrefix, message) {
  const whatsapp = whatsappUrl(message);
  return `    <a class="skip-link" href="#conteudo">Pular para o conteúdo</a>
    <header class="site-header" aria-label="Topo">
      <a class="brand" href="/" aria-label="ECVO início"><img class="brand-logo" src="${assetPrefix}assets/ecvo-simbolo-escuro.png" alt="" width="56" height="56" /><span class="brand-name"><strong>Escola de Combate</strong><span>Vinicius Oliveira</span></span></a>
      <nav aria-label="Navegação principal"><a href="/blog/">Conteúdos</a><a href="/#horarios">Horários</a><a href="/kickboxing-infantil-joao-pessoa/">Turma Kids</a><a class="nav-app-link" href="${whatsapp}" data-track="whatsapp_click" data-cta-position="header">Falar com a ECVO</a></nav>
    </header>`;
}

function renderFooter(assetPrefix, whatsapp) {
  return `    <footer><div class="footer-brand"><img class="brand-logo" src="${assetPrefix}assets/ecvo-simbolo-escuro.png" alt="" width="64" height="64" /><span class="brand-name"><strong>Escola de Combate</strong><span>Vinicius Oliveira</span></span></div><a href="/blog/">Ver todos os conteúdos</a><span class="footer-meta">João Pessoa · PB · © ECVO</span></footer>
    <a class="whatsapp-float" href="${whatsapp}" aria-label="Falar com a ECVO no WhatsApp" data-track="whatsapp_click" data-cta-position="floating">${whatsappIcon()}</a>`;
}

function renderBlock(block) {
  if (block.type === "p") return `<p>${block.html}</p>`;
  if (block.type === "list") return `<ul>${block.items.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`;
  if (block.type === "cadence") return `<div class="article-cadence">${block.items.map((item) => `<p>${escapeHtml(item)}</p>`).join("")}</div>`;
  if (block.type === "closing") return `<p class="article-closing">${block.html}</p>`;
  throw new Error(`Bloco de artigo desconhecido: ${block.type}`);
}

function renderHomeSection(post) {
  return `${homeStart}
      <aside class="section home-journal" aria-labelledby="home-journal-title">
        <div class="home-journal-art" data-reveal>
          <img src="${post.image.webp}" alt="${escapeHtml(post.image.alt)}" width="${post.image.width}" height="${post.image.height}" loading="lazy" decoding="async" />
        </div>
        <div class="home-journal-copy" data-reveal>
          <p class="eyebrow">Ciência &amp; artes marciais</p>
          <h2 id="home-journal-title">${escapeHtml(post.title)}</h2>
          <p>${escapeHtml(post.excerpt)}</p>
          <div class="home-journal-meta"><time datetime="${post.publishedAt}">${formatDate(post.publishedAt)}</time><span>${escapeHtml(post.readingTime)}</span></div>
          <a class="button primary" href="/blog/${post.slug}/">Ler o conteúdo <span class="button-arrow" aria-hidden="true">→</span></a>
        </div>
      </aside>
${homeEnd}`;
}

function renderBlogIndex(posts) {
  const url = "https://ecvo.com.br/blog/";
  const title = "Conteúdos sobre artes marciais | ECVO";
  const description = "Ciência, prática e cultura das artes marciais em conteúdos preparados pela ECVO para alunos, famílias e responsáveis.";
  const whatsapp = whatsappUrl("Olá! Li um conteúdo no site da ECVO e gostaria de saber mais sobre as aulas.");
  const schemas = [
    {
      "@context": "https://schema.org",
      "@type": "CollectionPage",
      "@id": `${url}#webpage`,
      name: title,
      description,
      url,
      isPartOf: { "@id": "https://ecvo.com.br/#website" },
    },
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Início", item: "https://ecvo.com.br/" },
        { "@type": "ListItem", position: 2, name: "Conteúdos", item: url },
      ],
    },
  ];

  const cards = posts.map((post, index) => `<article class="journal-card${index === 0 ? " journal-card--lead" : ""}">
          <a class="journal-card-art" href="/blog/${post.slug}/"><img src="${post.image.webp}" alt="" width="${post.image.width}" height="${post.image.height}" loading="${index === 0 ? "eager" : "lazy"}" decoding="async" /></a>
          <div class="journal-card-copy"><p class="eyebrow">${escapeHtml(post.eyebrow)}</p><h2><a href="/blog/${post.slug}/">${escapeHtml(post.title)}</a></h2><p>${escapeHtml(post.excerpt)}</p><div class="home-journal-meta"><time datetime="${post.publishedAt}">${formatDate(post.publishedAt)}</time><span>${escapeHtml(post.readingTime)}</span></div><a class="card-link" href="/blog/${post.slug}/">Ler o conteúdo <span aria-hidden="true">→</span></a></div>
        </article>`).join("\n");

  return `<!doctype html>
${generatedNote}
<html lang="pt-BR">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${title}</title>
    <meta name="description" content="${description}" />
    <link rel="canonical" href="${url}" />
    <meta property="og:title" content="${title}" />
    <meta property="og:description" content="${description}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="${url}" />
    <meta property="og:image" content="https://ecvo.com.br${posts[0].image.social}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${title}" />
    <meta name="twitter:description" content="${description}" />
    <meta name="twitter:image" content="https://ecvo.com.br${posts[0].image.social}" />
    <meta name="theme-color" content="#141414" />
    <link rel="icon" type="image/svg+xml" href="../assets/favicon.svg" />
    <link rel="apple-touch-icon" href="../assets/logo-ecvo-negativo.png" />
    <script type="application/ld+json">${jsonLd(schemas)}</script>
    <script>document.documentElement.classList.add("js");</script>
${renderFontHead("../")}
    <link rel="stylesheet" href="../styles.css?v=18" />
  </head>
  <body class="journal-page">
${renderHeader("../", "Olá! Li um conteúdo no site da ECVO e gostaria de saber mais sobre as aulas.")}
    <main id="conteudo">
      <nav class="breadcrumb" aria-label="Caminho de navegação"><ol><li><a href="/">Início</a></li><li aria-current="page">Conteúdos</li></ol></nav>
      <section class="journal-hero" aria-labelledby="journal-title"><p class="eyebrow"><span class="pulse"></span>Leitura para quem treina e para quem cuida</p><h1 id="journal-title">Ciência, prática e cultura marcial.</h1><p>Conteúdos para entender o que acontece dentro e fora do tatame — com responsabilidade, contexto e fontes.</p></section>
      <section class="section journal-list" aria-label="Conteúdos publicados">${cards}</section>
    </main>
${renderFooter("../", whatsapp)}
    <script src="../script.js?v=4"></script>
  </body>
</html>
`;
}

function renderPost(post) {
  const url = `https://ecvo.com.br/blog/${post.slug}/`;
  const pageTitle = `${post.title} | ECVO`;
  const whatsappMessage = "Olá! Li o conteúdo sobre artes marciais, autocontrole e agressividade e gostaria de conhecer a Turma Kids da ECVO.";
  const whatsapp = whatsappUrl(whatsappMessage);
  const schemas = [
    {
      "@context": "https://schema.org",
      "@type": "BlogPosting",
      "@id": `${url}#article`,
      headline: post.title,
      description: post.description,
      image: `https://ecvo.com.br${post.image.social}`,
      datePublished: post.publishedAt,
      dateModified: post.modifiedAt,
      inLanguage: "pt-BR",
      author: { "@type": "Organization", name: "ECVO", url: "https://ecvo.com.br/" },
      publisher: {
        "@type": "Organization",
        name: "ECVO",
        logo: { "@type": "ImageObject", url: "https://ecvo.com.br/assets/logo-ecvo-principal.png" },
      },
      mainEntityOfPage: { "@type": "WebPage", "@id": url },
      about: ["Artes marciais", "Autocontrole", "Agressividade infantil", "Desenvolvimento infantil"],
    },
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Início", item: "https://ecvo.com.br/" },
        { "@type": "ListItem", position: 2, name: "Conteúdos", item: "https://ecvo.com.br/blog/" },
        { "@type": "ListItem", position: 3, name: post.title, item: url },
      ],
    },
  ];

  const toc = post.sections.map((section) => `<li><a href="#${section.id}">${escapeHtml(section.title)}</a></li>`).join("");
  const sections = post.sections.map((section) => `<section id="${section.id}" class="article-section${section.accent ? " article-section--accent" : ""}" aria-labelledby="${section.id}-title">
              <p class="article-section-index" aria-hidden="true">${String(post.sections.indexOf(section) + 1).padStart(2, "0")}</p>
              <h2 id="${section.id}-title">${escapeHtml(section.title)}</h2>
              ${section.blocks.map(renderBlock).join("\n              ")}
            </section>`).join("\n");
  const references = post.references.map((reference, index) => `<li><span>${String(index + 1).padStart(2, "0")}</span><p><strong>${escapeHtml(reference.authors)} (${reference.year}).</strong> <cite>${escapeHtml(reference.title)}</cite> ${escapeHtml(reference.journal)} <a href="${reference.url}" target="_blank" rel="noopener noreferrer">${escapeHtml(reference.label)} <span class="sr-only">(abre em nova aba)</span></a></p></li>`).join("");

  return `<!doctype html>
${generatedNote}
<html lang="pt-BR">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(pageTitle)}</title>
    <meta name="description" content="${escapeHtml(post.description)}" />
    <link rel="canonical" href="${url}" />
    <meta property="og:title" content="${escapeHtml(pageTitle)}" />
    <meta property="og:description" content="${escapeHtml(post.description)}" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="${url}" />
    <meta property="og:image" content="https://ecvo.com.br${post.image.social}" />
    <meta property="og:image:width" content="${post.image.width}" />
    <meta property="og:image:height" content="${post.image.height}" />
    <meta property="article:published_time" content="${post.publishedAt}" />
    <meta property="article:modified_time" content="${post.modifiedAt}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escapeHtml(pageTitle)}" />
    <meta name="twitter:description" content="${escapeHtml(post.description)}" />
    <meta name="twitter:image" content="https://ecvo.com.br${post.image.social}" />
    <meta name="theme-color" content="#141414" />
    <link rel="icon" type="image/svg+xml" href="../../assets/favicon.svg" />
    <link rel="apple-touch-icon" href="../../assets/logo-ecvo-negativo.png" />
    <script type="application/ld+json">${jsonLd(schemas)}</script>
    <script>document.documentElement.classList.add("js");</script>
${renderFontHead("../../")}
    <link rel="stylesheet" href="../../styles.css?v=18" />
  </head>
  <body class="article-page">
${renderHeader("../../", whatsappMessage)}
    <main id="conteudo">
      <nav class="breadcrumb" aria-label="Caminho de navegação"><ol><li><a href="/">Início</a></li><li><a href="/blog/">Conteúdos</a></li><li aria-current="page">Ciência &amp; artes marciais</li></ol></nav>
      <article>
        <header class="article-hero">
          <div class="article-hero-copy">
            <p class="eyebrow"><span class="pulse"></span>${escapeHtml(post.eyebrow)}</p>
            <h1>${escapeHtml(post.title)}</h1>
            <p class="article-deck">${escapeHtml(post.description)}</p>
            <div class="article-meta"><span>Por ECVO</span><time datetime="${post.publishedAt}">${formatDate(post.publishedAt)}</time><span>${escapeHtml(post.readingTime)}</span></div>
          </div>
          <figure class="article-hero-art"><picture><source srcset="${post.image.webp}" type="image/webp" /><img src="${post.image.social}" alt="${escapeHtml(post.image.alt)}" width="${post.image.width}" height="${post.image.height}" fetchpriority="high" decoding="async" /></picture><figcaption>Resumo visual dos estudos apresentados neste conteúdo.</figcaption></figure>
        </header>

        <dl class="article-proof-strip">${post.takeaways.map((item) => `<div><dt>${escapeHtml(item.value)}</dt><dd>${escapeHtml(item.label)}</dd></div>`).join("")}</dl>

        <div class="article-layout">
          <aside class="article-toc" aria-label="Neste conteúdo"><p>Neste conteúdo</p><ol>${toc}<li><a href="#referencias">Referências científicas</a></li></ol></aside>
          <div class="article-body">
            <div class="article-answer"><p><strong>Resposta curta:</strong> não é isso que a evidência disponível sugere. Em programas estruturados, a prática pode favorecer autocontrole e autorregulação — capacidades importantes para reduzir respostas impulsivas e agressivas.</p></div>
            <div class="article-lead">${post.lead.map((paragraph) => `<p>${paragraph}</p>`).join("")}</div>
            ${sections}
            <section id="referencias" class="article-references" aria-labelledby="referencias-title"><p class="eyebrow">Fontes consultadas</p><h2 id="referencias-title">Referências científicas</h2><ol>${references}</ol><p class="article-source-note">Este conteúdo é informativo e resume resultados de estudos específicos. Ele não substitui avaliação individual de saúde, educação ou comportamento.</p></section>
          </div>
        </div>

        <section class="section article-cta" aria-labelledby="article-cta-title"><div><p class="eyebrow">Turma Kids · João Pessoa</p><h2 id="article-cta-title">Disciplina se aprende praticando.</h2><p>Conheça a proposta da ECVO para crianças e confirme a turma e os horários diretamente com a equipe.</p></div><div class="contact-actions"><a class="button primary" href="${whatsapp}" data-track="whatsapp_click" data-cta-position="article-final">Falar com a ECVO <span class="button-arrow" aria-hidden="true">→</span></a><a class="button secondary" href="/kickboxing-infantil-joao-pessoa/">Conhecer a Turma Kids</a></div></section>
      </article>
    </main>
${renderFooter("../../", whatsapp)}
    <script src="../../script.js?v=4"></script>
  </body>
</html>
`;
}

async function expectedFiles() {
  const home = await readFile(homeTarget, "utf8");
  const startIndex = home.indexOf(homeStart);
  const endIndex = home.indexOf(homeEnd);
  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    throw new Error("Marcadores do blog na homepage não foram encontrados.");
  }

  const nextHome = `${home.slice(0, startIndex)}${renderHomeSection(featuredBlogPost)}${home.slice(endIndex + homeEnd.length)}`;
  return [
    [homeTarget, nextHome],
    [resolve(blogDirectory, "index.html"), renderBlogIndex(blogPosts)],
    ...blogPosts.map((post) => [resolve(blogDirectory, post.slug, "index.html"), renderPost(post)]),
  ];
}

const files = await expectedFiles();

if (checkMode) {
  const mismatches = [];
  for (const [target, expected] of files) {
    const current = await readFile(target, "utf8").catch(() => "");
    if (current !== expected) mismatches.push(target.replace(`${root}/`, ""));
  }
  if (mismatches.length) {
    console.error(`Arquivos de blog fora de sincronia: ${mismatches.join(", ")}`);
    process.exitCode = 1;
  } else {
    console.log(`Blog validado: ${blogPosts.length} conteúdo publicado e chamada da homepage sincronizada.`);
  }
} else {
  for (const [target, contents] of files) {
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, contents);
  }
  console.log(`Blog gerado: ${blogPosts.length} conteúdo publicado e chamada da homepage atualizada.`);
}
